name: Run default tests
on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  tests-default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        target: [ 'jvmAll', 'js', 'wasm', 'native', 'connectedAndroid' ]
        include:
          - os: 'macos-latest'
            target: 'macos'
          - os: 'macos-latest'
            target: 'ios'
          - os: 'macos-latest'
            target: 'watchos'
          - os: 'macos-latest'
            target: 'tvos'
          - os: 'windows-latest'
            target: 'native'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment

      - name: Run tests
        if: ${{ matrix.target != 'connectedAndroid' }}
        run: ./gradlew ${{ matrix.target }}Test --continue

      - name: Run tests (android)
        if: ${{ matrix.target == 'connectedAndroid' }}
        uses: ./.github/actions/run-android-emulator-tests
        with:
          test-reports-classifier: 'default'
          run: ./gradlew ${{ matrix.target }}Test --continue
